#!/bin/sh
#
# enable lidar usb port
#

start() {
    nsenter --target 1 --mount -- env -i /etc/init.d/S13board_init start
}

case "$1" in
    start)
        start
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
esac

exit $?

