#!/bin/sh
#
# Start guppyflo
#

WORKDIR=/root/printer_software/guppyflo
GUPPYFLO=$WORKDIR/guppyflo
PID_FILE=/run/guppyflo.pid
NICENESS=10

start() {
    if [ -f $GUPPYFLO ]; then
	start-stop-daemon -S -b -m -p $PID_FILE -N $NICENESS --exec /bin/sh -- -c "cd $WORKDIR && $GUPPYFLO -c $WORKDIR"
    fi
}

stop() {
    start-stop-daemon -K -q -p $PID_FILE
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
